### ISSUE TITLE
not working with ubuntu-gnome 16.10

### ISSUE THREAD

**Issue by paulle** [biji/harddiskled#1]
Harddiskled not working with ubuntu-gnome 16.10. Don't show the the activity of the harddisc(s).

**Comment by biji** [comment]
what is the content of /proc/diskstats ?

**Comment by paulle** [comment]
1       0 ram0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 662 862 38079 1664 2 0 2 0 0 576 1664
   8       1 sda1 348 862 15055 664 2 0 2 0 0 444 664
   8       2 sda2 69 0 6192 316 0 0 0 0 0 240 316
   8       3 sda3 72 0 6216 284 0 0 0 0 0 220 284
   8       4 sda4 125 0 8256 340 0 0 0 0 0 308 340
   8      16 sdb 34700 1499 2376936 1124156 6540 2280 773088 73908 0 112236 1198160
   8      17 sdb1 76 0 6344 720 0 0 0 0 0 708 720
   8      18 sdb2 11224 490 1858776 387792 1205 877 392792 12016 0 92996 399916
   8      19 sdb3 71 0 6456 1020 0 0 0 0 0 908 1020
   8      20 sdb4 23109 1009 490168 729908 5114 1395 376880 52124 0 83028 782020
   8      21 sdb5 130 0 10768 4008 27 8 3416 104 0 3544 4112

The diskstats file is shown in nautilus with 0 bytes, but I can open it as you see above.

**Comment by biji** [comment]
Hmm could be permission problem. Can you cat /proc/diskstats in terminal as user (not root)

**Comment by paulle** [comment]
chris@yoyo1:~$ cat /proc/diskstats
   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 1302 862 38719 1892 2 0 2 0 0 664 1892
   8       1 sda1 988 862 15695 908 2 0 2 0 0 432 908
   8       2 sda2 69 0 6192 264 0 0 0 0 0 216 264
   8       3 sda3 72 0 6216 336 0 0 0 0 0 276 336
   8       4 sda4 125 0 8256 336 0 0 0 0 0 312 336
   8      16 sdb 42741 1529 2692640 1277292 16917 9298 2304640 475648 0 150712 1752916
   8      17 sdb1 76 0 6344 756 0 0 0 0 0 716 756
   8      18 sdb2 14336 555 2121432 416644 6398 5841 1504720 258976 0 104940 675612
   8      19 sdb3 71 0 6456 832 0 0 0 0 0 812 832
   8      20 sdb4 28048 974 544976 856092 9752 3457 799920 192256 0 99936 1048336
   8      21 sdb5 120 0 9008 2440 0 0 0 0 0 2416 2436

here is the cat /proc/diskstats as user

**Comment by biji** [comment]
sorry, can you re upload that again in gist?

**Comment by paulle** [comment]
excuse me, I'm a noob. What is gist and how to upload?

**Comment by paulle** [comment]
believe I found it. Is it ok this way?

**Comment by biji** [comment]
Pls post uploaded gist url or pastebin

Thanks

**Comment by biji** [comment]
please try latest version in github,
extensions.gnome.org haven't approved last changes

**Comment by paulle** [comment]
Can't try it now, because I'm not at home. In three weeks I'm back home.

Am 27. Februar 2017 08:16:51 MEZ schrieb biji <notifications@github.com>:
>please try latest version in github,
>extensions.gnome.org haven't approved last changes
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/biji/harddiskled/issues/1#issuecomment-282645226

-- 
K-9 Mail
