### ISSUE TITLE
Error with GNOME 3.38

### ISSUE THREAD

**Issue by gregorydk** [biji/harddiskled#11]
Needs a fix to work with GNOME 3.38.

Error: `No property x_fill on StBin`

**Comment by ChrisLauinger77** [comment]
commented out line 41 and 42 in extension.js and it `works`

//        x_fill: true,
//        y_fill: false,

**Comment by glaubersm** [comment]
> commented out line 41 and 42 in extension.js and it `works`
> 
> // x_fill: true,
> // y_fill: false,

it did not work for me on Arch + Gnome 3.38.1.

**Comment by billgrz** [comment]
Running Fedora Workstation 33, Gnome 3.38.1.  Upon logging into Gnome desktop, presented with a gray screen and mouse cursor for about 60 seconds, then returns to the login screen.  Logs show that Gnome has crashed.  Removing the HarddiskLED extension for Gnome 3.36 restored the proper operation of Gnome.  For whatever it's worth, if I use "Gnome Classic" as the destop manager, there's no problem with the extension installed.
