### ISSUE TITLE
Does not appear to work under Fedora 25

### ISSUE THREAD

**Issue by watchdogR** [biji/harddiskled#2]
Hi. I installed this extension, but when, for example, showing the contents of my NAS which contains a lot of data, the bytes count remained 0.
Cheers ... Ruud

**Comment by biji** [comment]
please attach screenshot

**Comment by biji** [comment]
and output of: /proc/diskstats

**Comment by biji** [comment]
Installed under Fedora 25 and it is working fine, please post your /proc/diskstats to pastebin

**Comment by biji** [comment]
please try latest version in github,
extensions.gnome.org haven't approved last changes
