### ISSUE TITLE
[Feature Request] Please provide support for GNOME 45.

### ISSUE THREAD

**Issue by billgrz** [biji/harddiskled#24]
As I understand it, GNOME 45 handles extensions differently than in previous versions. ( See https://linuxiac.com/gnome-45-breaks-extensions-compatibility/)
Please update your harddiskled extension accordingly, as many of us with laptops find it valuable.
Thank you!

**Comment by vibejamin** [comment]
I second that. 

It's a simple, but great extension which I'd hate to lose.

**Comment by billgrz** [comment]
Never mind.  I just discovered that you've already made the necessary changes for Gnome 45.  The issue is that the Gnome  Extensions web site does not yet have the newer version of HarddiskLED (v.35).  The solution, as reported elsewhere, is to install your extension manually.  For anyone interested, I followed the instructions here 
https://www.debugpoint.com/manual-installation-gnome-extension/
which worked perfectly.  Thanks, biji!
