### ISSUE TITLE
machine with multiple disks

### ISSUE THREAD

**Issue by rickysarraf** [biji/harddiskled#3]
Is the extension supported with multiple disks ? I don't think so because then there'd be multiple HDD indicators.

Can you make the block device, that you read from /proc/diskstats, to be configurable ?
Also, can you add support for reporting for multiple block devices ?

There are many use cases.

1. BTRFS volume with multiple block devices
2. LVM with multiple block devices
3. RAID with multiple block devices.
4. Above 3 stacked together.
5. Ram block devices
6. Many more use cases.

So, easiest would be if you could add some UI to let the user feed in the block device(s).

```
rrs@learner:/tmp$ cat /proc/diskstats 
   8       0 sda 23511 437 383717 162066 2349 321156 2586618 476146 0 58643 638190
   8       1 sda1 130 0 8560 173 0 0 0 0 0 146 173
   8       2 sda2 294 432 13025 590 2 0 2 0 0 236 590
   8       3 sda3 126 0 8528 160 0 0 0 0 0 133 160
   8       4 sda4 122 0 8496 156 0 0 0 0 0 126 156
   8       5 sda5 211 0 16669 433 0 0 0 0 0 380 433
   8       6 sda6 182 0 11282 293 7 1 64 6 0 210 300
   8       7 sda7 22348 5 312861 160043 2164 321155 2586552 473430 0 55616 633450
   8      16 sdb 177329 1327 10311435 207976 73864 56649 2610248 71246 0 65936 279173
 179       0 mmcblk0 551 112 20088 1303 0 0 0 0 0 743 1303
 179       1 mmcblk0p1 248 112 3268 450 0 0 0 0 0 300 450
 179       2 mmcblk0p2 246 0 12652 653 0 0 0 0 0 423 653
 254       0 dm-0 178534 0 10310562 235283 122632 0 2610248 585903 0 72800 821416
 254       1 dm-1 22298 0 311970 161733 323415 0 2586552 912315770 0 56876 912477640
 254       2 dm-2 238 0 10816 180 322953 0 2583592 912312993 0 17203 912313220
 254       3 dm-3 21939 0 300186 161476 450 0 2960 3120 0 39700 164600
   7       0 loop0 81 0 2352 33 0 0 0 0 0 30 30
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
 253       0 zram0 296 0 2368 0 1 0 8 0 0 0 0
2016-12-17 / 18:19:16 ♒♒♒  ☺  
```

**Comment by rickysarraf** [comment]
I don't know javascript, but as I understand this code, you are assuming that the device that has its 2nd field as 0, is the parent block device ?

https://github.com/biji/harddiskled/blob/master/extension.js#L103

**Comment by biji** [comment]
please try latest version in github,
extensions.gnome.org haven't approved last changes

**Comment by rickysarraf** [comment]
I think it is working now. But with reads and writes not distinguished, it is not very obvious.

Please have a look at https://extensions.gnome.org/extension/120/system-monitor/
They have reads and writes done very well.
