### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by highvoltage** [biji/harddiskled#5]
Thanks for this great extension! Would you consider creating tags in git so that releases can be tracked? I'm the packager for this extension in Debian (that also makes its way into Ubuntu/Mint/etc) and it would make it easier to make sure we have the latest release package rather than manually checking the commit history. Thanks!

**Comment by biji** [comment]
ok, done 
thanks

**Comment by highvoltage** [comment]
Thanks a lot!
